### ISSUE TITLE
Unable to install dependencies from requirements.txt

### ISSUE THREAD

**Issue by RedsTom** [MaxenceR26/GestMoney#3]
![image](https://user-images.githubusercontent.com/44524788/161633809-5601db8b-877f-46d9-b024-5466553851d5.png)

**Comment by banban60** [comment]
Hey, normalement tu n'as pas besoin d'installer les requirements, car un interpréteur est configuré de base, avec les bons modules préinstallés. Pour lancer l'appli tu dois ouvrir le fichier bin\launch_app.vbs

**Comment by banban60** [comment]
Alors je corrige ce que je viens de dire. On a pas encore push sur GitHub la bonne version fonctionnelle du projet. Je m'en occupe ce soir, et en attendant tu peux utiliser l'installer disponible sur le site si tu veux tester l'appli et que tu es sur Windows. Désolé du désagrément.

**Comment by MaxenceR26** [comment]
Bonjour, je me permet de rajouter quelque chose.. Dans la commande que vous avez réaliser il vous manque un "paramètre" afin que la commande fonctionne.

la bonne syntaxe : pip install -r requirements.txt

Ou sinon : py -m pip install -r requirements.txt
